const GET_CATEGORIES = 'GET_CATEGORIES[CATEGORY]';
const GET_MAIN_CATEGORIES = 'GET_MAIN_CATEGORIES[CATEGORY]';
const GET_TOP_SERVICES = 'GET_TOP_SERVICES[CATEGORY]';

export {GET_CATEGORIES, GET_MAIN_CATEGORIES, GET_TOP_SERVICES};
