const SET_ERROR = 'SET_ERROR';
const SIGNUP = 'SIGNUP[AUTH]';
const SIGNUP_EXTERNAL = 'SIGNUP_EXTERNAL[AUTH]';
const SIGNIN = 'SIGNIN[AUTH]';
const SIGNIN_EXTERNAL = 'SIGNIN_EXTERNAL[AUTH]';
const CHANGE_PASSWORD = 'CHANGE_PASSWORD[AUTH]';
const SET_USER_LANGUAGE = 'SET_USER_LANGUAGE[AUTH]';
const SET_SPECIALIST_TRANSPORT = 'SET_SPECIALIST_TRANSPORT[AUTH]';
const CHANGEUSER_PROFILE = 'CHANGEUSER_PROFILE[AUTH]';
const REFRESH_TOKEN = 'REFRESH_TOKEN[AUTH]';
const LOG_OUT = 'LOG_OUT[AUTH]';
const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST[AUTH]';
const SET_LOADING = 'SET_LOADING';
const ADD_USER_ACCOUNT = 'ADD_USER_ACCOUNT';

export {
  SET_ERROR,
  SIGNUP,
  SET_LOADING,
  ADD_USER_ACCOUNT,
  SIGNIN,
  CHANGE_PASSWORD,
  SET_USER_LANGUAGE,
  SET_SPECIALIST_TRANSPORT,
  CHANGEUSER_PROFILE,
  REFRESH_TOKEN,
  LOG_OUT,
  SIGNUP_EXTERNAL,
  SIGNIN_EXTERNAL,
  RESET_PASSWORD_REQUEST,
};
