const SET_SERVICES = 'SET_SERVICES[SPECIALIST]';
const GET_SERVICES = 'GET_SERVICES[SPECIALIST]';
const SET_WORKING_HOURS = 'SET_WORKING_HOURS[SPECIALIST]';
const CHANGE_DAY_SCHEDULE = 'CHANGE_DAY_SCHEDULE[SPECIALIST]';
const CHANGE_DAY_OFF = 'CHANGE_DAY_OFF[SPECIALIST]';
const SAVE_DAYS_OFF = 'SAVE_DAYS_OFF[SPECIALIST]';
const SET_PASSED_INTRO = 'SET_PASSED_INTRO[SPECIALIST]';
const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS[SPECIALIST]';
const SET_ONBOARDING_PROGRESS = 'SET_ONBOARDING_PROGRESS[SPECIALIST]';
const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE[SPECIALIST]';
const CHANGE_TRANSPORT = 'CHANGE_TRANSPORT[SPECIALIST]';
const GET_DATE_SCHEDULE = 'GET_DATE_SCHEDULE[SPECIALIST]';
const GET_DAY_OFF_FOR_CERTAIN_DATE = 'GET_DAY_OFF_FOR_CERTAIN_DATE[SPECIALIST]';
const SET_SCHEDULE_FOR_CERTAIN_DATE = 'SET_SCHEDULE_FOR_CERTAIN_DATE[SPECIALIST]';
const GET_BACKGROUND_CHECKER_URL = 'GET_BACKGROUND_CHECKER_URL[SPECIALIST]';
const GET_UPCOMING_TASKS = 'GET_UPCOMING_TASKS[SPECIALIST]';
const GET_HISTORY_TASKS = 'GET_HISTORY_TASKS[SPECIALIST]';
const CHANGE_TASK_STATUS = 'CHANGE_TASK_STATUS[SPECIALIST]';
const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST[SPECIALIST]';
const GET_AVAILABILITY = 'GET_AVAILABILITY[SPECIALIST]';
const CREATE_NEW_TASK = 'CREATE_NEW_TASK[SPECIALIST]';
const GET_SPECIALIST_CARDS = 'GET_SPECIALIST_CARDS[SPECIALIST]';
const GET_SPECIALIST_TOP_SERVICES = 'GET_SPECIALIST_TOP_SERVICES[SPECIALIST]';


export {
  SET_SERVICES,
  GET_SERVICES,
  SET_WORKING_HOURS,
  CHANGE_DAY_SCHEDULE,
  CHANGE_DAY_OFF,
  SAVE_DAYS_OFF,
  SET_PASSED_INTRO,
  GET_NOTIFICATIONS,
  SET_ONBOARDING_PROGRESS,
  CHANGE_LANGUAGE,
  CHANGE_TRANSPORT,
  GET_DATE_SCHEDULE,
  GET_DAY_OFF_FOR_CERTAIN_DATE,
  SET_SCHEDULE_FOR_CERTAIN_DATE,
  GET_BACKGROUND_CHECKER_URL,
  GET_UPCOMING_TASKS,
  GET_HISTORY_TASKS,
  CHANGE_TASK_STATUS,
  GET_CUSTOMER_LIST,
  GET_AVAILABILITY,
  CREATE_NEW_TASK,
  GET_SPECIALIST_CARDS,
  GET_SPECIALIST_TOP_SERVICES,
};
